In [ ]:
import sys



sys.path.insert(0, "../../../")


import phitter

In [2]:
simulation = phitter.simulation.ProcessSimulation()
simulation.add_process(
    prob_distribution="normal",
    parameters={"mu": 5, "sigma": 2},
    process_id="first",
    new_branch=True,
    number_of_products=10,
)
simulation.add_process(
    prob_distribution="exponential",
    parameters={"lambda": 4},
    process_id="second",
    previous_ids=["first"],
)
simulation.add_process(
    prob_distribution="exponential",
    parameters={"lambda": 4},
    process_id="ni_idea",
    previous_ids=["first"],
)
simulation.add_process(
    prob_distribution="exponential",
    parameters={"lambda": 4},
    process_id="ni_idea_2",
    previous_ids=["first"],
    number_of_products=15,
    number_of_servers=4,
)

simulation.add_process(
    prob_distribution="gamma",
    parameters={"alpha": 15, "beta": 3},
    process_id="third",
    new_branch=True,
)
# simulation.add_process("exponential", {"lambda": 4.3}, "nn", previous_ids=["third"])
simulation.add_process(
    prob_distribution="beta",
    parameters={"alpha": 1, "beta": 1, "A": 2, "B": 3},
    process_id="fourth",
    previous_ids=["second", "third"],
    number_of_products=2,
)
simulation.add_process(
    prob_distribution="exponential",
    parameters={"lambda": 4.3},
    process_id="nn",
    previous_ids=["third"],
)

simulation.add_process(
    prob_distribution="exponential",
    parameters={"lambda": 4.3},
    process_id="fifth",
    new_branch=True,
)
simulation.add_process(
    prob_distribution="exponential",
    parameters={"lambda": 4.3},
    process_id="sixth",
    previous_ids=["fourth", "ni_idea", "nn"],
)
simulation.add_process(
    prob_distribution="beta",
    parameters={"alpha": 1, "beta": 1, "A": 2, "B": 3},
    process_id="seventh",
    previous_ids=["fifth", "sixth", "ni_idea_2"],
)

In [3]:
simulation.run(10)

,first,second,ni_idea,ni_idea_2,third,fourth,nn,fifth,sixth,seventh,Total Simulation Time
0,54.107120,0.014236,0.211137,1.007016,82.847418,4.399301,0.359727,0.055951,0.102269,2.788315,90.137303
1,48.575292,0.248515,0.020803,1.596155,42.245946,5.339623,0.055667,0.224401,0.159593,2.576529,56.899552
2,53.034255,0.246061,0.504727,0.578695,45.276005,4.695092,0.035526,0.137817,0.662676,2.149304,60.787388
3,50.253973,0.049078,0.092433,0.752197,27.789921,4.734892,0.081959,0.346717,0.427035,2.274898,57.739876
4,41.431444,0.056270,0.034203,1.111601,25.363627,5.414378,0.089688,0.051747,0.038733,2.298123,49.238949
5,54.300688,1.034553,1.513765,1.228765,37.109152,4.428655,0.394619,0.347971,0.087520,2.214861,62.066276
6,50.496052,0.072799,0.279179,1.596274,51.638469,5.227044,0.111190,0.439075,0.117650,2.491412,59.474575
7,52.730428,0.056433,0.240337,1.324774,26.743012,4.517644,0.617136,0.094893,0.036723,2.111616,59.452844
8,46.447317,0.262300,0.667787,0.917990,50.463448,4.743344,0.087187,0.167567,0.135996,2.984129,58.326917
9,53.612717,0.798916,0.052226,1.287264,46.956782,4.882665,0.218880,0.294090,0.118071,2.450922,61.863291

In [4]:
simulation.simulation_metrics()

                            Metrics      Value
0                        Avg. first  50.498929
1                       Avg. second   0.283916
2                      Avg. ni_idea   0.361660
3                    Avg. ni_idea_2   1.140073
4                        Avg. third  43.643378
5                       Avg. fourth   4.838264
6                           Avg. nn   0.205158
7                        Avg. fifth   0.216023
8                        Avg. sixth   0.188626
9                      Avg. seventh   2.434011
10       Avg. Total Simulation Time  61.598697
11                  Std. Dev. first   4.095672
12                 Std. Dev. second   0.350849
13                Std. Dev. ni_idea   0.456722
14              Std. Dev. ni_idea_2   0.335527
15                  Std. Dev. third  16.920692
16                 Std. Dev. fourth   0.371162
17                     Std. Dev. nn   0.192089
18                  Std. Dev. fifth   0.135873
19                  Std. Dev. sixth   0.199559
20                Std. Dev. seventh   0.284577
21  Std. Dev. Total Simulation Time  10.671644

In [5]:
simulation.run_confidence_interval(number_of_simulations=100)

                            Metrics  LB - Value  AVG - Value  UB - Value
0        Avg. Total Simulation Time   61.018124    61.280457   61.542791
1                        Avg. fifth    0.217491     0.224921    0.232351
2                        Avg. first   49.820843    50.070130   50.319416
3                       Avg. fourth    4.980917     4.996120    5.011323
4                      Avg. ni_idea    0.245600     0.253506    0.261412
5                    Avg. ni_idea_2    1.202743     1.214488    1.226233
6                           Avg. nn    0.219101     0.228910    0.238719
7                       Avg. second    0.238955     0.248798    0.258640
8                      Avg. seventh    2.483429     2.493753    2.504077
9                        Avg. sixth    0.230105     0.238994    0.247883
10                       Avg. third   44.655332    45.019253   45.383174
11  Std. Dev. Total Simulation Time    7.282422     7.585355    7.888287
12                  Std. Dev. fifth    0.215793     0.226984    0.238174
13                  Std. Dev. first    6.293944     6.456508    6.619072
14                 Std. Dev. fourth    0.400565     0.410053    0.419542
15                Std. Dev. ni_idea    0.239864     0.251045    0.262226
16              Std. Dev. ni_idea_2    0.354997     0.367175    0.379353
17                     Std. Dev. nn    0.211469     0.224465    0.237460
18                 Std. Dev. second    0.240584     0.252148    0.263713
19                Std. Dev. seventh    0.279479     0.284548    0.289616
20                  Std. Dev. sixth    0.232646     0.244089    0.255533
21                  Std. Dev. third   11.379238    11.713891   12.048543